const fullAnswers={
'Tell me about yourself.':'I am a technology and digital transformation executive with more than 18 years of experience. I started in software engineering and grew into enterprise architecture, delivery leadership and national-scale transformation. Today I lead technology systems and digital transformation across healthcare and government, including a 54-person technology organization and an annual IT portfolio of about EGP 150M. My strongest example is the MedIQ transformation, where I connected strategy, architecture, delivery, integration, adoption and live operations. I am now looking for a wider mandate where I can create the same kind of measurable impact.',
'How would you describe your leadership style?':'My leadership style is clear, calm and accountable. I set direction, explain why it matters, define ownership and give people the space to deliver. I stay close to important risks and decisions, but I do not try to do the team’s work for them. I believe strong leaders create clarity, remove blockers, develop managers and make it safe for people to raise problems early.',
'What is your strongest technology leadership achievement?':'My strongest achievement is leading the transformation of MedIQ into a national procurement and supply ecosystem. The work covered re-architecture, rebuilding, migration, reconciliation, testing, training, cutover, stabilization and live operations. I also led a 54-person in-house technology organization through that journey. The result was not only a platform, but a more controlled, scalable and sustainable operating model.',
'How do you connect technology strategy to business outcomes?':'I start with the business or institutional outcome, not with a technology trend. I clarify the problem, users, constraints and measure of success, then translate that into capabilities, a roadmap, ownership, dependencies and investment decisions. During delivery I review adoption, reliability, cycle time, data quality and risk reduction, so the strategy stays connected to results.',
'Tell us about a complex transformation you led end to end.':'The MedIQ transformation is the clearest example. We moved from a complex operating environment to an integrated national platform covering procurement, tenders, delivery, inventory, assets, reporting and external integrations. My responsibility covered architecture, delivery governance, migration, reconciliation, testing, security, performance, training, parallel operation, cutover and stabilization. I treated production readiness and adoption as part of the transformation, not as activities after the project.',
'How do you make architecture decisions that survive production?':'I make boundaries, contracts, data ownership, security, observability and operational ownership explicit before implementation. I then test those decisions against delivery constraints, non-functional requirements and real operating scenarios. An architecture is successful when teams can build it, operations can run it and the business can depend on it.',
'How do you decide between microservices and a modular monolith?':'I do not choose microservices because they are fashionable. I look at domain boundaries, team ownership, deployment needs, failure isolation, data consistency and operational maturity. If independent scaling and ownership create real value, microservices may be appropriate. If the domain is changing quickly or the organization cannot operate the extra complexity, a modular monolith may be the more responsible choice.',
'How do you govern enterprise integration?':'I first agree who owns each business process and each important data element. Then I define interface contracts, master-data mapping, validation, security, error handling, monitoring, reconciliation and named owners for every handoff. I also make testing evidence and exceptions visible, so integration does not become a collection of technical connections with no accountability.',
'How do you approach ERP integration?':'ERP integration must start with the business process and control model. I align finance, procurement, inventory and technology owners, then define APIs, ETL, mappings, validation and reconciliation around platforms such as Dynamics 365 or SAP. I make sure SIT, UAT, security, cutover and support responsibilities are clear. The goal is reliable business synchronization, not simply moving data between systems.',
'How do you manage a technology portfolio with competing priorities?':'I make trade-offs visible. I compare initiatives by outcome, risk, urgency, dependencies, capacity and measurable value. I separate must-do work from useful work, identify what should stop or move, and communicate the decision clearly. A healthy portfolio explains both what is funded and why other work is waiting.',
'How do you lead a team through major change?':'I explain the reason for the change and what will be different for people. I involve the team in discovering risks, clarify roles and create practical milestones. I protect psychological safety so people can discuss problems early, while keeping standards and accountability clear. Communication, visible progress and coaching turn uncertainty into confidence.',
'How do you handle disagreement with a senior stakeholder?':'I keep the conversation focused on the decision, not on personalities. I listen carefully, bring evidence, explain options and make the consequences clear. If the final decision differs from my recommendation, I commit to it and help the team execute it well. This keeps challenge professional and trust intact.',
'Tell us about a delivery failure or setback.':'I first contain the immediate impact and protect users or operations. Then I look honestly at the signal we missed, the decisions that contributed to it and the root cause. I communicate the facts without blame and add a practical control, such as a better readiness gate or monitoring rule. The lesson must become institutional, not remain a personal story.',
'How do you measure whether digital transformation is working?':'I use more than delivery milestones. I look at adoption, cycle time, service reliability, data quality, user effort, control effectiveness, support demand and the intended business outcome. I compare these measures with the starting point and review them over time. This distinguishes a system that launched from a transformation that is creating value.',
'How do you build a high-performing engineering organization?':'I give the organization a clear mission and operating model. I set standards for architecture, quality, security, delivery and support, then make ownership and decision rights explicit. I invest in managers, coaching, hiring and feedback, while keeping the team connected to users and outcomes. High performance comes from clarity and healthy systems, not constant pressure.',
'How do you manage vendors and implementation partners?':'I define outcomes, scope, responsibilities and acceptance criteria before work starts. A clear RACI, interface ownership, milestones, SLA expectations and escalation path prevent confusion. I review evidence rather than status language and keep critical knowledge and architecture decisions inside the organization. Partners should increase capability, not create uncontrolled dependency.',
'How do you balance speed with security and compliance?':'I bring security and compliance into design and delivery early. I use risk-based controls such as least privilege, MFA, encryption, audit trails, secure development, testing and release gates. The level of control should match the risk, but important controls cannot be traded away for a short deadline. Good governance reduces late surprises.',
'How do you approach cloud and hybrid architecture?':'I place each workload according to data sensitivity, latency, resilience, integration, cost and operating capability. A hybrid design needs clear security, networking, monitoring, backup, disaster recovery and ownership. I define RTO and RPO expectations and make cost visible. The right architecture is the one the organization can run reliably over time.',
'How do you ensure data quality across integrated systems?':'I define the owner and meaning of each critical data element. I use a canonical model where appropriate, validate at boundaries, reconcile records, monitor exceptions and provide a remediation path. Data quality must be measured and visible, especially for procurement, inventory, finance and healthcare data.',
'How do you run a critical go-live?':'I use readiness criteria covering cutover, data reconciliation, rollback, security, performance, training, support, monitoring, communications and business sign-off. When possible I use parallel operation and a defined hypercare period. A go-live is successful when the organization can operate confidently after launch, not simply when deployment finishes.',
'What is your approach to PMO and delivery governance?':'I see governance as decision support, not paperwork. I want a clear view of milestones, RAID items, dependencies, quality gates, benefits, decisions and actions. Reporting should be concise for executives and useful for delivery teams. A good PMO helps leaders act early and keeps accountability visible.',
'How do you communicate technical risk to executives?':'I explain the business consequence first. I state the probability, options, recommendation, owner and decision date in plain language. I avoid unnecessary technical detail, but I do not hide uncertainty. Executives should leave knowing what is at risk and what decision will reduce it.',
'How do you improve adoption of a new platform?':'I involve users before the design is finished and understand how work is really done. I measure friction, design by role, train people on real scenarios, provide support and use feedback to improve the product. Adoption grows when the platform is useful, trusted and supported by managers and operating processes.',
'What would your first 90 days in this role look like?':'I would listen to leaders, users and delivery teams and map the operating model, priorities, risks and dependencies. I would validate the strategy and agree a small number of measurable outcomes. I would deliver one visible improvement while building the roadmap, governance rhythm and stakeholder alignment for the larger agenda. The plan would be evidence-led and practical.',
'Why are you considering a new role?':'I am looking for a wider mandate where technology strategy, architecture, delivery and transformation outcomes are connected at greater scale. I have built strong experience leading complex platforms and teams, and I want to apply it where the next level of impact is possible. I am not moving away from delivery; I want to own more of the transformation outcome.',
'Why should we choose you for this position?':'I bring engineering depth, executive accountability, enterprise architecture, delivery governance and national-scale transformation experience. I can discuss strategy with executives and challenge an integration design, readiness plan or production risk with technical teams. Most importantly, I turn ambiguity into clear decisions, owned execution and measurable outcomes.'
};
const qGrid=document.getElementById('question-grid');
function applyFullAnswers(){qGrid?.querySelectorAll('.question-card').forEach(card=>{const t=card.querySelector('h3')?.textContent?.trim();if(fullAnswers[t])card.querySelector('.answer').textContent=fullAnswers[t]});if(!qGrid||qGrid.querySelector('[data-opener]'))return;const opener=document.createElement('article');opener.className='question-card is-top opener-card';opener.dataset.opener='true';opener.innerHTML='<div class="card-meta"><span class="category">Opening question</span><span class="priority">START HERE</span></div><h3>Tell me about yourself.</h3><span class="answer-label">ANSWER ANCHOR</span><p class="answer">'+fullAnswers['Tell me about yourself.']+'</p><div class="keywords"><span>18+ years</span><span>technology executive</span><span>MedIQ</span><span>54-person team</span><span>transformation</span></div>';qGrid.prepend(opener)}
new MutationObserver(applyFullAnswers).observe(qGrid,{childList:true});applyFullAnswers();
