import {readFile,readdir,stat} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {generateSearchMatrix,parseCSV} from '../assets/data.js';
import {MATRIX_TARGET,DATASETS,VERSION} from '../assets/config.js';

const required=['index.html','today.html','explore.html','africa-ngos.html','africa-map.html','dashboard.html','tracker.html','review-queue.html','contacts.html','documents.html','version-history.html','calendar.html','weekly-review.html','ats-connectors.html','save-from-web.html','opportunities.html','consulting.html','rosters.html','volunteer-secondments.html','requirements.html','templates.html','email-importer.html','profile-coverage.html','rules.html','archive.html','vault.html','analytics.html','quality.html','settings.html','link-checker.html','sources.html','methodology.html','job-search-platforms.html','assets/source-intelligence.js','data/source-packs.json','data/source-directory.csv','api/fetch-feed.js','api/ats-jobs.js','api/detect-ats.js','assets/ats.js','assets/capture.js','assets/calendar.js','assets/version-history.js','assets/weekly.js','assets/opportunity-core.js','assets/opportunity-pages.js','assets/vault.js','assets/archive.js','assets/eligibility.js','assets/security.js','assets/filter-client.js','assets/filter-worker.js','assets/app.css','assets/pages.js','assets/source-intelligence.js','assets/renderer.js','assets/tracker.js','assets/productivity.js','assets/localdb.js','assets/scoring.js','data/seed.json','api/check-link.js','api/snapshot.js','api/fetch-feed.js','manifest.webmanifest','sw.js','README.md'];
let failed=false;
for(const file of required){try{const s=await stat(resolve(file));if(!s.size)throw new Error('empty');console.log(`✓ ${file}`)}catch(error){failed=true;console.error(`✗ ${file}: ${error.message}`)}}
for(const removed of ['search.html','alerts.html','api/ai-search.js','assets/search-engine.js']){try{await stat(resolve(removed));failed=true;console.error(`✗ removed feature still present: ${removed}`)}catch{console.log(`✓ removed: ${removed}`)}}
const matrix=generateSearchMatrix();if(matrix.length!==MATRIX_TARGET){failed=true;console.error(`✗ matrix count ${matrix.length} != ${MATRIX_TARGET}`)}else console.log(`✓ matrix count ${matrix.length.toLocaleString()}`);
const seed=JSON.parse(await readFile(resolve('data/seed.json'),'utf8'));
for(const [key,config] of Object.entries(DATASETS)){if(!Array.isArray(seed[key])||!seed[key].length){failed=true;console.error(`✗ missing seed dataset ${key}`)}else console.log(`✓ seed ${key}: ${seed[key].length}`);try{const offline=parseCSV(await readFile(resolve('data/offline',config.file),'utf8'));if(offline.length!==config.target){failed=true;console.error(`✗ offline ${key}: ${offline.length} != ${config.target}`)}else console.log(`✓ offline ${key}: ${offline.length.toLocaleString()}`)}catch(error){failed=true;console.error(`✗ offline ${key}: ${error.message}`)}}
const html=(await readdir('.')).filter(x=>x.endsWith('.html'));
for(const file of html){const text=await readFile(file,'utf8');if(!text.includes('assets/pages.js')){failed=true;console.error(`✗ ${file} missing shared application script`)}if(!text.includes('Content-Security-Policy')){failed=true;console.error(`✗ ${file} missing CSP`)}if(/\son[a-z]+=["']/i.test(text)){failed=true;console.error(`✗ ${file} contains inline event handler`)}if(/<script(?![^>]*\bsrc=)[^>]*>[\s\S]*?\S[\s\S]*?<\/script>/i.test(text)){failed=true;console.error(`✗ ${file} contains inline script`)}for(const match of text.matchAll(/(?:href|src)=["']\.\/([^"'#?]+)["']/g)){const target=resolve(dirname(file),match[1]);try{await stat(target)}catch{failed=true;console.error(`✗ ${file} missing internal target ${match[1]}`)}}}
const css=await readFile(resolve('assets/app.css'),'utf8');const cssDefs=new Set([...css.matchAll(/--([\w-]+)\s*:/g)].map(x=>x[1])),cssUses=new Set([...css.matchAll(/var\(--([\w-]+)/g)].map(x=>x[1])),undefinedCSS=[...cssUses].filter(x=>!cssDefs.has(x));if(undefinedCSS.length){failed=true;console.error(`✗ undefined CSS variables: ${undefinedCSS.join(', ')}`)}else console.log(`✓ CSS variables: ${cssDefs.size} defined, none missing`);
const combined=await Promise.all(['assets/config.js','assets/pages.js','assets/source-intelligence.js','assets/renderer.js','assets/tracker.js','assets/productivity.js','assets/localdb.js','api/check-link.js','api/snapshot.js','api/fetch-feed.js','api/ats-jobs.js','api/detect-ats.js','assets/ats.js','assets/capture.js','assets/calendar.js','assets/version-history.js','assets/weekly.js','assets/opportunity-core.js','assets/opportunity-pages.js','assets/vault.js','assets/archive.js','assets/eligibility.js','assets/security.js'].map(f=>readFile(resolve(f),'utf8'))).then(x=>x.join('\n'));
for(const forbidden of ['openai','ai-powered','api/ai-search','search-engine.js'])if(combined.toLowerCase().includes(forbidden)){failed=true;console.error(`✗ removed AI reference: ${forbidden}`)}
for(const feature of ['initToday','initContacts','initDocuments','initAnalytics','initQuality','initAfricaMap','initSettings','SYNONYM_GROUPS','EXCLUSION_OPTIONS','createAutomaticBackup','addAttachment','saveSnapshot','careerSignals','duplicateGroups','applicationAnalytics','data-view="compact"','initSourceIntelligence','sourceAuthorityRank','remoteEligibility','jobAttributes','officialFirstGroups','sourcePerformance','RSS and alert importer','Official Sources First','initATSConnectors','detectATSFromUrl','assessEligibility','eligibilityAdjustedMatch','organizationPriority','initCapture','initCalendar','initVersionHistory','initWeeklyReview','listSnapshotVersions','snapshotVersions','Export .ics','Weekly Review','ATS Connectors','Save to Career Hub','initOpportunityTracks','initConsulting','initRosters','initRequirements','initTemplates','initEmailImporter','initProfileCoverage','initRules','initArchive','initVault','decisionScore','OPPORTUNITY_TRACKS','encryptPortableBackup','opportunityArchive']){if(!combined.includes(feature)){failed=true;console.error(`✗ missing local-productivity feature: ${feature}`)}else console.log(`✓ feature: ${feature}`)}
if(/AVAILABILITY_STATUSES[^\n]*Not Available/.test(combined)){failed=true;console.error('✗ Not Available is still a vacancy availability status')}else console.log('✓ Not Available remains personal-only');

const sw=await readFile(resolve('sw.js'),'utf8'),shellMatch=sw.match(/const SHELL=\[([\s\S]*?)\];/),shellItems=shellMatch?[...shellMatch[1].matchAll(/'([^']+)'/g)].map(x=>x[1]):[];for(const item of shellItems){const rel=item.replace(/^\.\//,'')||'.';try{await stat(resolve(rel))}catch{failed=true;console.error(`✗ service worker missing cached file: ${item}`)}}if(shellItems.length)console.log(`✓ service worker shell: ${shellItems.length} files`);
const sourceCSV=parseCSV(await readFile(resolve('job-search-platforms.csv'),'utf8'));
if(sourceCSV.length!==DATASETS.platforms.target){failed=true;console.error(`✗ named source count ${sourceCSV.length} != ${DATASETS.platforms.target}`)}else console.log(`✓ named source directory: ${sourceCSV.length}`);
if(sourceCSV.some(x=>/generated/i.test(x.source||'')||/live search/i.test(x.type||''))){failed=true;console.error('✗ generated searches remain in named source directory')}else console.log('✓ source directory contains named sources only');
for(const row of sourceCSV){try{new URL(row.url)}catch{failed=true;console.error(`✗ invalid source URL: ${row.title}`)}}
const official=sourceCSV.filter(x=>Number(x.sourceRank)>=6).length,specialist=sourceCSV.filter(x=>Number(x.sourceRank)===5).length,rss=sourceCSV.filter(x=>x.rssUrl).length;
if(official<20||specialist<4||rss<5){failed=true;console.error(`✗ source coverage too low: official=${official}, specialist=${specialist}, rss=${rss}`)}else console.log(`✓ source coverage: ${official} official, ${specialist} specialist, ${rss} RSS-enabled`);

const mandatorySources=['ICRC Careers','IFRC Careers','Norwegian Refugee Council Careers','NORCAP Expert Deployments','Danish Refugee Council Careers','Oxfam International Careers','Oxfam in Africa Jobs','Plan International Careers','Médecins Sans Frontières Careers','International Medical Corps Careers'];
for(const name of mandatorySources){if(!sourceCSV.some(x=>x.title===name)){failed=true;console.error(`✗ missing humanitarian source: ${name}`)}else console.log(`✓ humanitarian source: ${name}`)}

const packs=JSON.parse(await readFile(resolve('data/source-packs.json'),'utf8'));if(packs.length<6){failed=true;console.error('✗ missing source packs')}else console.log(`✓ source packs: ${packs.length}`);

const ngoCSV=parseCSV(await readFile(resolve('africa-ngos.csv'),'utf8'));if(ngoCSV.length!==148){failed=true;console.error(`✗ Africa NGO count ${ngoCSV.length} != 148`)}else console.log('✓ Africa NGO directory: 148 named records');
console.log(`Version: ${VERSION}`);if(failed)process.exit(1);console.log(`Validation complete: ${html.length} HTML pages, ${Object.keys(DATASETS).length} datasets.`);
