
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const page=document.body.dataset.page||'home';
const STORE={theme:'ms-hub-theme',fav:'ms-hub-favorites',status:'ms-hub-status',apps:'ms-hub-applications',contacts:'ms-hub-contacts'};
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const load=async p=>{
  const key=String(p).split('/').pop().replace(/\.json$/,'').replace(/-/g,'_');
  if(window.CAREER_DATA&&Object.prototype.hasOwnProperty.call(window.CAREER_DATA,key)){
    return window.CAREER_DATA[key];
  }
  const r=await fetch(p);
  if(!r.ok)throw new Error(p);
  return r.json();
};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function shell(){const root=document.documentElement;root.dataset.theme=get(STORE.theme,'light');$('#themeBtn').onclick=()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';set(STORE.theme,root.dataset.theme)};$('#menuBtn').onclick=()=>$('#navLinks').classList.toggle('open');$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===page));}
function statusValue(r){return get(STORE.status,{})[r.id]||r.availability_status||'Monitoring'}
function saveStatus(id,v){const all=get(STORE.status,{});all[id]=v;set(STORE.status,all);toast('Status saved')}
function favValue(id){return new Set(get(STORE.fav,[])).has(id)}
function toggleFav(id){const s=new Set(get(STORE.fav,[]));s.has(id)?s.delete(id):s.add(id);set(STORE.fav,[...s]);toast(s.has(id)?'Saved':'Removed')}
function qs(name){return new URLSearchParams(location.search).get(name)||''}
function card(r,kind){const official=r.source_quality==='A',priority=r.is_priority||r.priority_tier==='Priority 1';const title=r.title||'';const org=r.organization||r.industry||'';const meta=kind==='job'?[r.country,r.location,r.role_family,r.published_date]:kind==='employer'?[r.industry,r.region,r.priority_tier,r.last_checked]:[r.type,r.region,r.priority_tier,r.last_checked];const opts=kind==='employer'?['Career Page Available','Monitoring','Priority Employer','Not Available']:['Available','Monitoring','Interested','Applied','Interview','Offer','Rejected','Not Available'];return `<article class="card ${priority?'priority':''}"><div class="card-top"><div class="badges">${priority?'<span class="badge gold">Priority</span>':''}<span class="badge ${official?'a':'warn'}">${official?'Official':'Platform'}</span><span class="badge">${esc(r.type||r.role_family||kind)}</span></div><button class="secondary" data-fav="${r.id}" aria-label="Save">${favValue(r.id)?'★':'☆'}</button></div><h3>${esc(title)}</h3><div class="org">${esc(org)}</div><div class="meta">${meta.filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('')}</div><p class="notes">${esc(r.notes||'Open the source and verify current availability before applying.')}</p><div class="actions"><a class="button" href="${esc(r.url)}" target="_blank" rel="noopener">${kind==='employer'?'Careers':'Open source'}</a><select data-status="${r.id}">${opts.map(x=>`<option ${statusValue(r)===x?'selected':''}>${x}</option>`).join('')}</select></div></article>`}
function bindCards(){$$('[data-status]').forEach(x=>x.onchange=()=>saveStatus(x.dataset.status,x.value));$$('[data-fav]').forEach(x=>x.onclick=()=>{toggleFav(x.dataset.fav);x.textContent=favValue(x.dataset.fav)?'★':'☆'})}
async function home(){const [m,e,j,r]=await Promise.all([load('./data/manifest.json'),load('./data/featured-employers.json'),load('./data/featured-jobs.json'),load('./data/recommended-resources.json')]);$('#metrics').innerHTML=[['Priority employers',m.counts.priority_employers],['Official current jobs',m.counts.official_jobs],['Job resources',m.counts.resources],['Project opportunities',m.counts.projects]].map(x=>`<div class="metric"><strong>${Number(x[1]).toLocaleString()}</strong><span>${x[0]}</span></div>`).join('');const cats={};e.forEach(x=>cats[x.industry]=(cats[x.industry]||0)+1);$('#categories').innerHTML=Object.entries(cats).slice(0,8).map(([k,v])=>`<a class="category-card" href="./employers.html?industry=${encodeURIComponent(k)}"><span class="count">${v}</span><b>${esc(k)}</b><span>Explore major employers</span></a>`).join('');$('#featuredEmployers').innerHTML=e.slice(0,9).map(x=>card(x,'employer')).join('');$('#featuredJobs').innerHTML=j.slice(0,6).map(x=>card(x,'job')).join('');$('#featuredResources').innerHTML=r.slice(0,12).map(x=>`<a class="resource-link" href="${esc(x.url)}" target="_blank"><b>${esc(x.title)}</b><span>${esc(x.region)}</span></a>`).join('');bindCards();$('#heroSearch').onsubmit=e=>{e.preventDefault();const mode=$('#searchMode').value,q=$('#heroQuery').value.trim();location.href=`./${mode}.html?q=${encodeURIComponent(q)}`}}
function listingConfig(){if(page==='jobs')return{file:'jobs.json',kind:'job',fields:['title','organization','role_family','country','location','notes','source'],title:'job'};if(page==='employers')return{file:'employers.json',kind:'employer',fields:['title','industry','region','country','notes'],title:'employer'};if(page==='resources')return{file:'platforms.json',kind:'resource',fields:['title','type','region','notes'],title:'resource'};if(page==='projects')return{file:'projects.json',kind:'job',fields:['title','organization','type','region','country','notes'],title:'project'}}
async function listing(){const c=listingConfig(),data=await load('./data/'+c.file);let pageNo=1;const per=24;const qEl=$('#q'),f1=$('#filter1'),f2=$('#filter2'),f3=$('#filter3'),sort=$('#sort');qEl.value=qs('q');if(c.kind==='employer'&&qs('industry'))f1.dataset.pending=qs('industry');const vals=(field)=>[...new Set(data.map(x=>x[field]).filter(Boolean))].sort();if(c.kind==='job'){fill(f1,vals('region'),'All regions');fill(f2,vals('role_family'),'All role families');fill(f3,vals('availability_status'),'All availability')}else if(c.kind==='employer'){fill(f1,vals('industry'),'All industries');fill(f2,vals('region'),'All regions');fill(f3,['Priority 1','Directory'],'All employers')}else{fill(f1,vals('type'),'All types');fill(f2,vals('region'),'All regions');fill(f3,['Recommended','Directory'],'All resources')}if(f1.dataset.pending)f1.value=f1.dataset.pending;function fill(el,a,label){el.innerHTML=`<option value="">${label}</option>`+a.map(v=>`<option>${esc(v)}</option>`).join('')}function filtered(){const q=qEl.value.trim().toLowerCase();let a=data.filter(r=>{const hay=c.fields.map(k=>r[k]||'').join(' ').toLowerCase();if(q&&!hay.includes(q))return false;if(c.kind==='job'){if(f1.value&&r.region!==f1.value)return false;if(f2.value&&r.role_family!==f2.value)return false;if(f3.value&&r.availability_status!==f3.value)return false}else if(c.kind==='employer'){if(f1.value&&r.industry!==f1.value)return false;if(f2.value&&r.region!==f2.value)return false;if(f3.value&&r.priority_tier!==f3.value)return false}else{if(f1.value&&r.type!==f1.value)return false;if(f2.value&&r.region!==f2.value)return false;if(f3.value&&r.priority_tier!==f3.value)return false}return true});if(sort.value==='name')a.sort((x,y)=>(x.title||'').localeCompare(y.title||''));else if(sort.value==='match')a.sort((x,y)=>(y.match_score||0)-(x.match_score||0));else a.sort((x,y)=>(y.is_priority?1:0)-(x.is_priority?1:0)||(y.source_quality==='A'?1:0)-(x.source_quality==='A'?1:0));return a}function render(){const a=filtered(),pages=Math.max(1,Math.ceil(a.length/per));pageNo=Math.min(pageNo,pages);$('#resultCount').textContent=`${a.length.toLocaleString()} results`;$('#cards').innerHTML=a.slice((pageNo-1)*per,pageNo*per).map(x=>card(x,c.kind==='resource'?'resource':c.kind)).join('')||'<div class="empty">No matching records.</div>';$('#pagination').innerHTML=[1,pageNo-1,pageNo,pageNo+1,pages].filter((v,i,z)=>v>=1&&v<=pages&&z.indexOf(v)===i).map(n=>`<button class="${n===pageNo?'active':''}" data-p="${n}">${n}</button>`).join('');$$('[data-p]').forEach(b=>b.onclick=()=>{pageNo=+b.dataset.p;render();scrollTo({top:0,behavior:'smooth'})});bindCards()}[qEl,f1,f2,f3,sort].forEach(x=>x.oninput=()=>{pageNo=1;render()});$('#filterToggle').onclick=()=>$('#filters').classList.toggle('open');$('#clearFilters').onclick=()=>{qEl.value='';f1.value=f2.value=f3.value='';render()};render()}
async function resources(){await listing();const t=await load('./data/search-templates.json');$('#searchPlatform').innerHTML=t.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join('');$('#resourceBuilder').onsubmit=e=>{e.preventDefault();const x=t[+$('#searchPlatform').value],q=encodeURIComponent($('#resourceQuery').value.trim()),loc=encodeURIComponent($('#resourceLocation').value.trim()||'Egypt');open(x.url.replace('{q}',q).replace('{loc}',loc),'_blank')}}
function tracker(){const all=get(STORE.apps,{}),rows=Object.values(all);$('#trackerRows').innerHTML=rows.map(r=>`<tr data-id="${r.id}"><td>${esc(r.title)}</td><td>${esc(r.organization)}</td><td><select data-appstatus>${['Interested','Applied','Interview','Offer','Rejected','Not Available'].map(x=>`<option ${r.status===x?'selected':''}>${x}</option>`).join('')}</select></td><td><input type="date" data-follow value="${esc(r.follow||'')}"></td><td><input data-note value="${esc(r.note||'')}"></td><td><button class="secondary" data-delete>×</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Use the status menu on job cards to build your tracker.</td></tr>';$('#trackerRows').onchange=e=>{const tr=e.target.closest('tr'),a=get(STORE.apps,{}),r=a[tr.dataset.id]||{};if(e.target.matches('[data-appstatus]'))r.status=e.target.value;if(e.target.matches('[data-follow]'))r.follow=e.target.value;if(e.target.matches('[data-note]'))r.note=e.target.value;a[tr.dataset.id]=r;set(STORE.apps,a);toast('Tracker updated')};$('#trackerRows').onclick=e=>{if(e.target.matches('[data-delete]')){const tr=e.target.closest('tr'),a=get(STORE.apps,{});delete a[tr.dataset.id];set(STORE.apps,a);tr.remove()}}}
function contacts(){function render(){const a=get(STORE.contacts,[]);$('#contactRows').innerHTML=a.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.company)}</td><td>${esc(x.role)}</td><td>${esc(x.email)}</td><td>${esc(x.follow)}</td><td><button class="secondary" data-del="${x.id}">×</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No contacts saved.</td></tr>';$$('[data-del]').forEach(b=>b.onclick=()=>{set(STORE.contacts,a.filter(x=>x.id!==b.dataset.del));render()})}$('#contactForm').onsubmit=e=>{e.preventDefault();const a=get(STORE.contacts,[]);a.push({id:(globalThis.crypto&&crypto.randomUUID?crypto.randomUUID():'contact-'+Date.now()+'-'+Math.random().toString(16).slice(2)),name:$('#cName').value,company:$('#cCompany').value,role:$('#cRole').value,email:$('#cEmail').value,follow:$('#cFollow').value});set(STORE.contacts,a);e.target.reset();render();toast('Contact saved')};render()}
function enhanceJobTracking(){document.addEventListener('change',e=>{if(e.target.matches('[data-status]')&&['Interested','Applied','Interview','Offer','Rejected'].includes(e.target.value)){const id=e.target.dataset.status;const card=e.target.closest('.card');const all=get(STORE.apps,{});all[id]={id,title:$('h3',card)?.textContent||'',organization:$('.org',card)?.textContent||'',status:e.target.value,follow:'',note:''};set(STORE.apps,all)}})}
shell();enhanceJobTracking();if(page==='home')home();else if(['jobs','employers','projects'].includes(page))listing();else if(page==='resources')resources();else if(page==='tracker')tracker();else if(page==='contacts')contacts();

window.addEventListener('unhandledrejection',event=>{
  console.error(event.reason);
  const cards=document.querySelector('#cards');
  if(cards&&!cards.children.length){
    cards.innerHTML='<div class="empty">The data could not be loaded. Please confirm that data.js is uploaded beside this page.</div>';
  }
});
